apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-virtual-host
spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80
    - host: queue.fleetman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: queue
              servicePort: 8161