apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fleetman-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - http:
      paths:
          - path: /
            backend:
              serviceName: fleetman-webapp
              servicePort: 80
          - path: /queue
            backend:
              serviceName: fleetman-queue
              servicePort: 8161