apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fleetman-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - http:
      paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80
          - path: /queue
            backend:
              serviceName: queue
              servicePort: 8161