apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fleetman-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    ingress.kubernetes.io/rewrite-target: /activemq
spec:
  rules:
  - http:
      paths:
          - path: /activemq/*
            backend:
              serviceName: fleetman-queue
              servicePort: 8161
          - path: /*
            backend:
              serviceName: fleetman-webapp
              servicePort: 80
